from steamship import Steamship
from time import time
client = Steamship(workspace="gpt-4")
generator = client.use_plugin('gpt-4')

text='''Now I am going to give you a sentence where each word has a probability of appearing correctly in the sentence. 
Please edit the sign glosses and give me a sentence that makes sense and also follows the greek sign language grammar. 
You should remove the repeated glosses and do not change the order of the appearing glosses. 
Feel free to delete the words with lower probability if you think that's necessary. 
Remember, the most important thing is following the greek sign language grammar and let the edited sentence make sense. 
Give me 10 choices each with a confidence score between 0-1.Notice that the words and probabilities 
are generated by an imperfect sign gloss recognition model and I am going to use your answer as labels to train the 
recognition model. Also, do not change the order of the words!! 
hello 0.6320772767066956 okay 0.5458082556724548 hello 0.7298985719680786 hello 0.9473420977592468 
hello 0.5917715430259705 okay 0.4432564079761505 me 0.8909943103790283 me 0.9755492210388184 
me 0.9506744742393494 me 0.933338463306427 okay 0.4987574815750122 okay 0.6472973227500916 
good 0.4142535626888275 can 0.9953546524047852 can 0.8891858458518982 trousers 0.6230805516242981 
help 0.25329720973968506 help 0.9473912715911865 help 0.9961116909980774 help 0.9868718385696411 
help 0.9940887689590454. Just give me answers in the form of sentence:score, no other things.'''


start = time()
task = generator.generate(text=text)
task.wait()
message = task.output.blocks[0].text
print(message)
end = time()
print(end-start)